name: plant-mechinterp-rev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - torch
      - torchvision
      - transformers
      - accelerate
      - datasets
      - huggingface_hub
      - numpy
      - pandas
      - pyarrow
      - scikit-learn
      - scipy
      - statsmodels
      - matplotlib
      - seaborn
      - tqdm
      - requests
      - biopython
      - pyfaidx
      - gffutils
      - pyBigWig
